name: My First Workflow

on: push

jobs: 
    first-jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Welcome Ike, your first Github Actions Job!"

        - name: List file
          run: ls
        
        - name: Read file
          run: cat README.md

          