name: My First Workflow

on: push

jobs: 
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: Welcome message
          run: |
            echo "Welcome Ike, your first Github Actions Job!"
            ls -ltra
            cat README.md
        # lets add 3rd party content to generate ascii
        - name: Generate ASCII
          run: cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR"  >> dragon.txt
        #- name: List file
        # run: ls
        #- name: Read file
        # run: cat README.md

          